# Generated by Django 2.1 on 2018-08-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='form_type',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
    ]
