# Generated by Django 2.0.7 on 2018-07-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='proposition',
            name='type',
            field=models.CharField(default='', max_length=1),
        ),
    ]
