# Generated by Django 2.0.7 on 2018-07-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0002_auto_20180729_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='type',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
