# Generated by Django 2.0.7 on 2018-07-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0003_auto_20180729_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='type',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
