# Generated by Django 2.0.7 on 2018-08-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0005_auto_20180730_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='type',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='type',
        ),
    ]
