# Generated by Django 2.0.7 on 2018-08-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0006_auto_20180803_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='type',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='type',
        ),
    ]
