# Generated by Django 2.0.7 on 2018-08-03 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0007_auto_20180803_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
