# Generated by Django 2.0.7 on 2018-08-03 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0008_proof_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='created_date',
        ),
        migrations.AddField(
            model_name='proposition',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
